# from django.core.exceptions import ValidationError
# from datetime import date

# def validate_past_date(value):
#     if value > date.today:
#       raise ValidationError("This date cannot be in the past")
#     return value